export type {
  Lead,
  CallLog,
  Callback,
  CallbackWithLead,
  Disposition,
  LeadType,
  CallState,
  SessionStatus,
  ImportResult,
  SessionStats,
  DuplicateLead,
  CallIntelligenceStats,
  CallLogWithLead,
  PipelineStage,
  Temperature,
  Note,
  Project,
  ProjectStatus,
  Activity,
  ActivityType,
  EmailSent,
  EmailDraft,
  EmailDraftStatus,
  EmailDraftWithLead,
} from '@shared/types';
